services:
  webui:
    build: ./webui
    container_name: lensql_client_webui
    ports:
      - "8888:80"
    depends_on:
      - server

      
  server:
    # image: davideponzini/lensql_server:1
    build: ./server
    container_name: lensql_client_server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      LENSQL_HOST: https://ponzidav.com/lensql
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: password

  db:
    image: postgres:latest
    container_name: lensql_client_db
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - lensql_client_pgdata:/var/lib/postgresql/data

volumes:
  lensql_client_pgdata:
